version: '2'
services:
    camera-app:
        image: camera
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://camera-mysql:3306/camera?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    camera-mysql:
        extends:
            file: mysql.yml
            service: camera-mysql
